version: '3.8'

services: 
  app-gateway:
    container_name: app-gateway
    build:
      context: ./app-gateway
    ports:
      - 3000:3000
    command: npm run start:dev
    depends_on:
      - rabbitmq
    restart: always


  profile:
    container_name: app-profile
    build:
      context: ./profile
    command: npm run start:dev
    depends_on:
      - postgresProfile
      - rabbitmq
    restart: always

  user:
    container_name: app-user
    build:
      context: ./user
    command: npm run start:dev
    depends_on:
      - postgresUser
      - rabbitmq
    restart: always

  postgresUser:
    container_name: postgresUser
    image: postgres:latest
    environment:
      POSTGRES_DB: "user"
      POSTGRES_PASSWORD: qwerty
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - dataUser:/var/lib/postgresql/data
    restart: always

  postgresProfile:
    container_name: postgresProfile
    image: postgres:latest
    environment:
      POSTGRES_DB: "profile"
      POSTGRES_PASSWORD: qwerty
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - dataProf:/var/lib/postgresql/data
    restart: always

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672
    restart: always

volumes:
  dataUser:
  dataProf:
